conn / as sysdba
ALTER SYSTEM SET db_recovery_file_dest_size = 5G;
HOST mkdir /opt/oracle/oradata/recovery_area
ALTER SYSTEM SET db_recovery_file_dest = '/opt/oracle/oradata/recovery_area' scope=spfile;
ALTER SYSTEM SET enable_goldengate_replication=true;
SHUTDOWN IMMEDIATE
STARTUP MOUNT
ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;
CREATE TABLESPACE xstream_adm_tbs DATAFILE '/opt/oracle/oradata/CDB193/xstream_adm_tbs.dbf' SIZE 25M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;
CREATE TABLESPACE xstream_tbs DATAFILE '/opt/oracle/oradata/CDB193/xstream_tbs.dbf' SIZE 25M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;
CREATE TABLESPACE logminer_tbs DATAFILE '/opt/oracle/oradata/CDB193/logminer_tbs.dbf' SIZE 25M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;
ALTER SESSION SET CONTAINER = pdb193;
CREATE TABLESPACE xstream_adm_tbs DATAFILE '/opt/oracle/oradata/CDB193/PDB193/xstream_adm_tbs.dbf' SIZE 25M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;
CREATE TABLESPACE xstream_tbs DATAFILE '/opt/oracle/oradata/CDB193/PDB193/xstream_tbs.dbf' SIZE 25M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;
CREATE TABLESPACE logminer_tbs DATAFILE '/opt/oracle/oradata/CDB193/PDB193/logminer_tbs.dbf' SIZE 25M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;
ALTER SESSION SET CONTAINER = cdb$root;
CREATE USER c##xstrmadmin IDENTIFIED BY xsa DEFAULT TABLESPACE xstream_adm_tbs QUOTA UNLIMITED ON xstream_adm_tbs CONTAINER=ALL;
GRANT CREATE SESSION, SET CONTAINER TO c##xstrmadmin CONTAINER=ALL;
CREATE USER c##xstrm IDENTIFIED BY xs DEFAULT TABLESPACE xstream_tbs QUOTA UNLIMITED ON xstream_tbs CONTAINER=ALL;
GRANT CREATE SESSION, SET CONTAINER, FLASHBACK ANY TABLE, SELECT_CATALOG_ROLE TO c##xstrm CONTAINER=ALL;
GRANT SELECT ON V_$DATABASE to c##xstrm CONTAINER=ALL;
CREATE USER c##logminer IDENTIFIED BY lm DEFAULT TABLESPACE logminer_tbs QUOTA UNLIMITED ON logminer_tbs CONTAINER=ALL;
GRANT CREATE SESSION, SET CONTAINER, FLASHBACK ANY TABLE, LOCK ANY TABLE, CREATE TABLE, CREATE SEQUENCE, LOGMINING TO c##logminer CONTAINER=ALL;
GRANT SELECT ON V_$DATABASE to c##logminer CONTAINER=ALL;
GRANT SELECT ON V_$LOG TO c##logminer CONTAINER=ALL;
GRANT EXECUTE ON DBMS_LOGMNR TO c##logminer CONTAINER=ALL;
GRANT EXECUTE ON DBMS_LOGMNR_D TO c##logminer CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_LOGS TO c##logminer CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_CONTENTS TO c##logminer CONTAINER=ALL;
GRANT SELECT ON V_$LOGFILE TO c##logminer CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVED_LOG TO c##logminer CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVE_DEST_STATUS TO c##logminer CONTAINER=ALL;
GRANT SELECT_CATALOG_ROLE TO c##logminer CONTAINER=ALL;
GRANT SELECT ANY TABLE TO c##logminer CONTAINER=ALL;
DECLARE
  tables  DBMS_UTILITY.UNCL_ARRAY;
  schemas DBMS_UTILITY.UNCL_ARRAY;
BEGIN
    tables(1)  := NULL;
    schemas(1) := 'debezium';
  DBMS_XSTREAM_ADM.CREATE_OUTBOUND(
    server_name     =>  'dbzxout',
    table_names     =>  tables,
    schema_names    =>  schemas);
END;
/
BEGIN
  DBMS_XSTREAM_ADM.ALTER_OUTBOUND(
    server_name  => 'dbzxout',
    connect_user => 'c##xstrm');
END;
/
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER SESSION SET CONTAINER = pdb193;
CREATE USER debezium IDENTIFIED BY dbz;
GRANT CONNECT TO debezium;
GRANT CREATE SESSION TO debezium;
GRANT CREATE TABLE TO debezium;
GRANT CREATE SEQUENCE TO debezium;
ALTER USER debezium QUOTA 100M ON users;
